[build-system]
requires = [
    "scikit-build-core>=0.10",
    "pybind11>=2.12",
]
build-backend = "scikit_build_core.build"


[project]
name = "thermoplume"
version = "0.1.0"
description = "Thermodynamic models for volcanic plume neutral buoyancy and external water interaction"
requires-python = ">=3.10"
license = { file = "LICENSE" }

dependencies = [
    "numpy",
    "scipy",
]


[tool.scikit-build]
wheel.packages = ["src/thermoplume"]
cmake.build-type = "Release"